version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  kubernetes:
    lang: runner-template-python3
    handler: ./kubernetes
    image: kubiya/action-store-k8s:latest
    annotations:
        topic: "kubernetes"
        com.openfaas.serviceaccount: default
